import os

SERVICE_NAME = 'history-agent'
MAX_PAGE_SIZE = min(int(os.getenv('MAX_PAGE_SIZE', '200')), 200)
DEFAULT_PAGE_SIZE = min(int(os.getenv('DEFAULT_PAGE_SIZE', '50')), 200)
DEFAULT_SLA_HOURS = int(os.getenv('DEFAULT_SLA_HOURS', '4'))
REOPEN_STALE_AFTER_HOURS = int(os.getenv('REOPEN_STALE_AFTER_HOURS', '24'))
DEFAULT_ALERT_CONTEXT_HOURS = int(os.getenv('DEFAULT_ALERT_CONTEXT_HOURS', '24'))
ALERTMANAGER_POLL_CONFIG_PATH = os.getenv('ALERTMANAGER_POLL_CONFIG_PATH', '/app/config/alertmanager_poll.json')
ALERTMANAGER_POLL_ENABLED = os.getenv('ALERTMANAGER_POLL_ENABLED', 'false').lower() in {'1', 'true', 'yes', 'on'}
ALERTMANAGER_URL = os.getenv('ALERTMANAGER_URL', 'http://alertmanager:9093')
ALERTMANAGER_POLL_INTERVAL_SECONDS = max(5, int(os.getenv('ALERTMANAGER_POLL_INTERVAL_SECONDS', '10')))
ALERTMANAGER_POLL_TIMEOUT_SECONDS = max(1, float(os.getenv('ALERTMANAGER_POLL_TIMEOUT_SECONDS', '10')))
ALERTMANAGER_POLL_VERIFY_TLS = os.getenv('ALERTMANAGER_POLL_VERIFY_TLS', 'true').lower() not in {'0', 'false', 'no', 'off'}
ALERTMANAGER_POLL_PROXY_URL = os.getenv('ALERTMANAGER_POLL_PROXY_URL', '')
